export const movies = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/14QbnygCuTO0vl7CAFmPf1fgZfV.jpg',
      genre_ids: [28, 12, 878],
      id: 634649,
      original_language: 'en',
      original_title: 'Spider-Man: No Way Home',
      overview:
        'Peter Parker is unmasked and no longer able to separate his normal life from the high-stakes of being a super-hero. When he asks for help from Doctor Strange the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.',
      popularity: 857.567,
      poster_path: '/uJYYizSuA9Y3DCs0qS4qWvHfZg4.jpg',
      release_date: '2021-12-15',
      title: 'Spider-Man: No Way Home',
      video: false,
      vote_average: 8,
      vote_count: 15686,
    },
    {
      adult: false,
      backdrop_path: '/a8tH0jl37366bLVyPB08dncgqqd.jpg',
      genre_ids: [10751, 35, 28],
      id: 654974,
      original_language: 'en',
      original_title: 'Home Sweet Home Alone',
      overview:
        'After being left at home by himself for the holidays, 10-year-old Max Mercer must work to defend his home from a married couple who tries to steal back a valuable heirloom.',
      popularity: 79.686,
      poster_path: '/fP3VvqUjEBjawxZHL4sYCq2ZdJD.jpg',
      release_date: '2021-11-12',
      title: 'Home Sweet Home Alone',
      video: false,
      vote_average: 5,
      vote_count: 446,
    },
    {
      adult: false,
      backdrop_path: '/jqVFrhFLqrOn72TImJuIzYWKByv.jpg',
      genre_ids: [14, 35, 16, 878, 10751],
      id: 228161,
      original_language: 'en',
      original_title: 'Home',
      overview:
        'When Earth is taken over by the overly-confident Boov, an alien race in search of a new place to call home, all humans are promptly relocated, while all Boov get busy reorganizing the planet. But when one resourceful girl, Tip, manages to avoid capture, she finds herself the accidental accomplice of a banished Boov named Oh. The two fugitives realize there’s a lot more at stake than intergalactic relations as they embark on the road trip of a lifetime.',
      popularity: 49.702,
      poster_path: '/usFenYnk6mr8C62dB1MoAfSWMGR.jpg',
      release_date: '2015-03-18',
      title: 'Home',
      video: false,
      vote_average: 6.8,
      vote_count: 3459,
    },
    {
      adult: false,
      backdrop_path: '/dBt0DoFfbhOI4ypUfRj1uTq623M.jpg',
      genre_ids: [27, 9648, 53],
      id: 521029,
      original_language: 'en',
      original_title: 'Annabelle Comes Home',
      overview:
        "Determined to keep Annabelle from wreaking more havoc, demonologists Ed and Lorraine Warren bring the possessed doll to the locked artifacts room in their home, placing her “safely” behind sacred glass and enlisting a priest’s holy blessing. But an unholy night of horror awaits as Annabelle awakens the evil spirits in the room, who all set their sights on a new target—the Warrens' ten-year-old daughter, Judy, and her friends.",
      popularity: 130.605,
      poster_path: '/qWsHMrbg9DsBY3bCMk9jyYCRVRs.jpg',
      release_date: '2019-06-26',
      title: 'Annabelle Comes Home',
      video: false,
      vote_average: 6.4,
      vote_count: 2896,
    },
    {
      adult: false,
      backdrop_path: '/4kui3QA55M2ZOmBgoRlrYj5MSlK.jpg',
      genre_ids: [35],
      id: 274167,
      original_language: 'en',
      original_title: "Daddy's Home",
      overview:
        "The story of a mild-mannered radio executive who strives to become the best stepdad ever to his wife's two children, but complications ensue when their freewheeling, freeloading real father arrives, forcing stepdad to compete for the affection of the kids.",
      popularity: 37.307,
      poster_path: '/fB9lALk9zKsMYWvf0bJSkJN219Z.jpg',
      release_date: '2015-12-25',
      title: "Daddy's Home",
      video: false,
      vote_average: 6.3,
      vote_count: 2739,
    },
    {
      adult: false,
      backdrop_path: '/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg',
      genre_ids: [28, 12, 878],
      id: 429617,
      original_language: 'en',
      original_title: 'Spider-Man: Far from Home',
      overview:
        'Peter Parker and his friends go on a summer trip to Europe. However, they will hardly be able to rest - Peter will have to agree to help Nick Fury uncover the mystery of creatures that cause natural disasters and destruction throughout the continent.',
      popularity: 95.204,
      poster_path: '/4q2NNj4S5dG2RLF9CpXsej7yXl.jpg',
      release_date: '2019-06-28',
      title: 'Spider-Man: Far from Home',
      video: false,
      vote_average: 7.5,
      vote_count: 13265,
    },
    {
      adult: false,
      backdrop_path: '/jRi6AKMPLnMtsFtWY0FUXZOlnVb.jpg',
      genre_ids: [35],
      id: 419680,
      original_language: 'en',
      original_title: "Daddy's Home 2",
      overview:
        'Brad and Dusty must deal with their intrusive fathers during the holidays.',
      popularity: 37.624,
      poster_path: '/rF2IoKL0IFmumEXQFUuB8LajTYP.jpg',
      release_date: '2017-11-09',
      title: "Daddy's Home 2",
      video: false,
      vote_average: 6.3,
      vote_count: 2163,
    },
    {
      adult: false,
      backdrop_path: '/c8Woa2lNy3RuWW2IVEiOud3kevh.jpg',
      genre_ids: [10751, 35],
      id: 817648,
      original_language: 'en',
      original_title: 'Home Team',
      overview:
        'Two years after a Super Bowl win when NFL head coach Sean Payton is suspended, he goes back to his hometown and finds himself reconnecting with his 12-year-old son by coaching his Pop Warner football team.',
      popularity: 41.432,
      poster_path: '/xdPdVJGIQjuVhK7SeK5fpjuc1bu.jpg',
      release_date: '2022-01-28',
      title: 'Home Team',
      video: false,
      vote_average: 6.8,
      vote_count: 576,
    },
    {
      adult: false,
      backdrop_path: '/rsVf3VqUk7kOnQgfIr5rmSYhmFc.jpg',
      genre_ids: [16, 28, 10751, 35, 878],
      id: 979296,
      original_language: 'en',
      original_title: 'Sonic Drone Home',
      overview:
        'Sonic, Tails, and Knuckles encounter an abandoned Badnik drone which upgraded itself using parts from a junkyard, with the intention of conquering the world.',
      popularity: 44.545,
      poster_path: '/ifc2YN7eZeHKwaoiT0Xn8LiJCFb.jpg',
      release_date: '2022-05-24',
      title: 'Sonic Drone Home',
      video: false,
      vote_average: 6.7,
      vote_count: 25,
    },
    {
      adult: false,
      backdrop_path: '/6gvocf4kU9qJyUVZEDveOtLkaMu.jpg',
      genre_ids: [35, 10751, 10770],
      id: 12536,
      original_language: 'en',
      original_title: 'Home Alone 4',
      overview:
        "Kevin McCallister's parents have split up. Now living with his mom, he decides to spend Christmas with his dad at the mansion of his father's rich girlfriend, Natalie. Meanwhile robber Marv Merchants, one of the villains from the first two movies, partners up with a new criminal named Vera to hit Natalie's mansion.",
      popularity: 36.588,
      poster_path: '/lL2Ri3PHs9V1ot3V8ZUvrtFgj9h.jpg',
      release_date: '2002-11-03',
      title: 'Home Alone 4',
      video: false,
      vote_average: 4.5,
      vote_count: 1027,
    },
    {
      adult: false,
      backdrop_path: '/zG8CP8iRhLo7BNBsma6GfP6gkRF.jpg',
      genre_ids: [35, 10751],
      id: 9714,
      original_language: 'en',
      original_title: 'Home Alone 3',
      overview:
        '9-year-old Alex Pruitt is home alone with the chicken pox. Turns out, due to a mix-up among nefarious spies, Alex was given a toy car concealing a top-secret microchip. Now Alex must fend off the spies as they try to break into his house to get it back.',
      popularity: 40.797,
      poster_path: '/6uOadrCfle0n2LOOxHbgWEdnrm2.jpg',
      release_date: '1997-12-12',
      title: 'Home Alone 3',
      video: false,
      vote_average: 5.3,
      vote_count: 2547,
    },
    {
      adult: false,
      backdrop_path: '/2kmAwtw3RqFX0vJq7hKrIkGth1L.jpg',
      genre_ids: [53, 27],
      id: 792657,
      original_language: 'en',
      original_title: 'Safer at Home',
      overview:
        'Two years into the pandemic, a group of friends throw an online party with a night of games, drinking and drugs. After taking an ecstasy pill, things go terribly wrong and the safety of their home becomes more terrifying than the raging chaos outside.',
      popularity: 40.212,
      poster_path: '/2mfnSVdDartB6TJ3k7Qyn0zMzKu.jpg',
      release_date: '2021-02-26',
      title: 'Safer at Home',
      video: false,
      vote_average: 5.6,
      vote_count: 118,
    },
    {
      adult: false,
      backdrop_path: '/1hrexCNSKU8SZ2rgl2UvBvcqs1M.jpg',
      genre_ids: [53, 27],
      id: 525460,
      original_language: 'en',
      original_title: 'Welcome Home',
      overview:
        "A couple try to repair their damaged union in an Italian vacation paradise. Then they discover the owner's intentions.",
      popularity: 25.013,
      poster_path: '/fMhJQoMitAh0pN0fLlD7iUGcBp0.jpg',
      release_date: '2018-11-16',
      title: 'Welcome Home',
      video: false,
      vote_average: 5.2,
      vote_count: 282,
    },
    {
      adult: false,
      backdrop_path: '/rQKlcMY8i3elENXEHlkAbQr3xiG.jpg',
      genre_ids: [16, 10751],
      id: 13700,
      original_language: 'en',
      original_title: 'Home on the Range',
      overview:
        'When a greedy outlaw schemes to take possession of the "Patch Of Heaven" dairy farm, three determined cows, a karate-kicking stallion and a colorful corral of critters join forces to save their home. The stakes are sky-high as this unlikely animal alliance risk their hides and match wits with a mysterious band of bad guys.',
      popularity: 47.83,
      poster_path: '/9xIIo4FMquy5SRqn8hppyr2QadR.jpg',
      release_date: '2004-04-02',
      title: 'Home on the Range',
      video: false,
      vote_average: 6,
      vote_count: 1711,
    },
    {
      adult: false,
      backdrop_path: '/w7MsyOpP003FYhsiTgVHa3rNsrz.jpg',
      genre_ids: [18, 12, 10751],
      id: 508763,
      original_language: 'en',
      original_title: "A Dog's Way Home",
      overview:
        'The adventure of Bella, a dog who embarks on an epic 400-mile journey home after she is separated from her beloved human.',
      popularity: 30.064,
      poster_path: '/pZn87R7gtmMCGGO8KeaAfZDhXLg.jpg',
      release_date: '2019-01-10',
      title: "A Dog's Way Home",
      video: false,
      vote_average: 7.3,
      vote_count: 938,
    },
    {
      adult: false,
      backdrop_path: '/xzXPybvwRXGIU5Bbw68YHVkTUW2.jpg',
      genre_ids: [35, 18, 10749],
      id: 427900,
      original_language: 'en',
      original_title: 'Home Again',
      overview:
        'Life for a single mom in Los Angeles takes an unexpected turn when she allows three young guys to move in with her.',
      popularity: 19.355,
      poster_path: '/pE4VHzhDZgvbx2QOllaXXPADiW1.jpg',
      release_date: '2017-09-07',
      title: 'Home Again',
      video: false,
      vote_average: 6.1,
      vote_count: 1083,
    },
    {
      adult: false,
      backdrop_path: '/ld7V9BjMk2xtiBNcR8savyyk5ca.jpg',
      genre_ids: [14, 12, 10751, 18],
      id: 283366,
      original_language: 'en',
      original_title: "Miss Peregrine's Home for Peculiar Children",
      overview:
        'A teenager finds himself transported to an island where he must help protect a group of orphans with special powers from creatures intent on destroying them.',
      popularity: 69.039,
      poster_path: '/6lSkpu2SDj71KTBy2DllM6CaFYA.jpg',
      release_date: '2016-09-27',
      title: "Miss Peregrine's Home for Peculiar Children",
      video: false,
      vote_average: 6.8,
      vote_count: 8922,
    },
    {
      adult: false,
      backdrop_path: '/78kinIgDGZ8KiKrK1BJBEiwNeBi.jpg',
      genre_ids: [99],
      id: 62320,
      original_language: 'fr',
      original_title: 'Home',
      overview:
        "In 200,000 years of existence, man has upset the balance on which the Earth had lived for 4 billion years. Global warming, resource depletion, species extinction: man has endangered his own home. But it is too late to be pessimistic: humanity has barely ten years left to reverse the trend, become aware of its excessive exploitation of the Earth's riches, and change its consumption pattern.",
      popularity: 11.412,
      poster_path: '/vf9giK9WawPGluWw5E3eyDreDcW.jpg',
      release_date: '2009-06-03',
      title: 'Home',
      video: false,
      vote_average: 7.9,
      vote_count: 408,
    },
    {
      adult: false,
      backdrop_path: '/vfdkUySTAyjugOJ9LvgDfH3JpWg.jpg',
      genre_ids: [53, 9648],
      id: 502167,
      original_language: 'en',
      original_title: 'Don’t Leave Home',
      overview:
        'An American artist’s obsession with a disturbing urban legend leads her to an investigation of the story’s origins at the crumbling estate of a reclusive painter in Ireland.',
      popularity: 15.618,
      poster_path: '/3Y296xLDoTOsts35P3dGErBrZbL.jpg',
      release_date: '2018-03-10',
      title: 'Don’t Leave Home',
      video: false,
      vote_average: 4.8,
      vote_count: 44,
    },
    {
      adult: false,
      backdrop_path: '/gxwYr2jtBzMvp85lbCr9ooJMFPc.jpg',
      genre_ids: [35, 10751, 12],
      id: 772,
      original_language: 'en',
      original_title: 'Home Alone 2: Lost in New York',
      overview:
        "Instead of flying to Florida with his folks, Kevin ends up alone in New York, where he gets a hotel room with his dad's credit card—despite problems from a clerk and meddling bellboy. But when Kevin runs into his old nemeses, the Wet Bandits, he's determined to foil their plans to rob a toy store on Christmas eve.",
      popularity: 75.274,
      poster_path: '/uuitWHpJwxD1wruFl2nZHIb4UGN.jpg',
      release_date: '1992-11-19',
      title: 'Home Alone 2: Lost in New York',
      video: false,
      vote_average: 6.7,
      vote_count: 7999,
    },
  ],
  total_pages: 221,
  total_results: 4413,
};
