export const movies = [
  {
    adult: false,
    backdrop_path: '/w9eBtIHHpGgGfjqnEAJM3s7mCOa.jpg',
    belongs_to_collection: {
      id: 328,
      name: 'Jurassic Park Collection',
      poster_path: '/jcUXVtJ6s0NG0EaxllQCAUtqdr0.jpg',
      backdrop_path: '/njFixYzIxX8jsn6KMSEtAzi4avi.jpg',
    },
    budget: 73000000,
    genres: [
      {
        id: 12,
        name: 'Adventure',
      },
      {
        id: 28,
        name: 'Action',
      },
      {
        id: 878,
        name: 'Science Fiction',
      },
    ],
    homepage: '',
    id: 330,
    imdb_id: 'tt0119567',
    original_language: 'en',
    original_title: 'The Lost World: Jurassic Park',
    overview:
      "Four years after Jurassic Park's genetically bred dinosaurs ran amok, multimillionaire John Hammond shocks chaos theorist Ian Malcolm by revealing that he has been breeding more beasties at a secret location. Malcolm, his paleontologist ladylove and a wildlife videographer join an expedition to document the lethal lizards' natural behavior in this action-packed thriller.",
    popularity: 2.313,
    poster_path: '/jElpCJkSaRPYwIMwZY28gOKV7BK.jpg',
    production_companies: [
      {
        id: 33,
        logo_path: '/8lvHyhjr8oUKOOy2dKXoALWKdp0.png',
        name: 'Universal Pictures',
        origin_country: 'US',
      },
      {
        id: 56,
        logo_path: '/cEaxANEisCqeEoRvODv2dO1I0iI.png',
        name: 'Amblin Entertainment',
        origin_country: 'US',
      },
      {
        id: 76068,
        logo_path: null,
        name: 'Digital Image Associates',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1997-05-23',
    revenue: 618638999,
    runtime: 129,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: 'Something has survived.',
    title: 'The Lost World: Jurassic Park',
    video: false,
    vote_average: 6.517,
    vote_count: 7172,
  },
  {
    adult: false,
    backdrop_path: '/rr7E0NoGKxvbkb89eR1GwfoYjpA.jpg',
    belongs_to_collection: null,
    budget: 63000000,
    genres: [
      {
        id: 18,
        name: 'Drama',
      },
      {
        id: 53,
        name: 'Thriller',
      },
      {
        id: 35,
        name: 'Comedy',
      },
    ],
    homepage: 'http://www.foxmovies.com/movies/fight-club',
    id: 550,
    imdb_id: 'tt0137523',
    original_language: 'en',
    original_title: 'Fight Club',
    overview:
      'A ticking-time-bomb insomniac and a slippery soap salesman channel primal male aggression into a shocking new form of therapy. Their concept catches on, with underground "fight clubs" forming in every town, until an eccentric gets in the way and ignites an out-of-control spiral toward oblivion.',
    popularity: 96.934,
    poster_path: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    production_companies: [
      {
        id: 508,
        logo_path: '/7cxRWzi4LsVm4Utfpr1hfARNurT.png',
        name: 'Regency Enterprises',
        origin_country: 'US',
      },
      {
        id: 711,
        logo_path: '/tEiIH5QesdheJmDAqQwvtN60727.png',
        name: 'Fox 2000 Pictures',
        origin_country: 'US',
      },
      {
        id: 4700,
        logo_path: '/A32wmjrs9Psf4zw0uaixF0GXfxq.png',
        name: 'The Linson Company',
        origin_country: 'US',
      },
      {
        id: 20555,
        logo_path: '/hD8yEGUBlHOcfHYbujp71vD8gZp.png',
        name: 'Taurus Film',
        origin_country: 'DE',
      },
      {
        id: 54051,
        logo_path: null,
        name: 'Atman Entertainment',
        origin_country: '',
      },
      {
        id: 54052,
        logo_path: null,
        name: 'Knickerbocker Films',
        origin_country: 'US',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'DE',
        name: 'Germany',
      },
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1999-10-15',
    revenue: 100853753,
    runtime: 139,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: 'Mischief. Mayhem. Soap.',
    title: 'Fight Club',
    video: false,
    vote_average: 8.427,
    vote_count: 25100,
  },
  {
    adult: false,
    backdrop_path: '/goQ3L7Gzh65A1gcQHeZJxAaQAW8.jpg',
    belongs_to_collection: null,
    budget: 0,
    genres: [
      {
        id: 35,
        name: 'Comedy',
      },
      {
        id: 18,
        name: 'Drama',
      },
    ],
    homepage: 'http://www.sommervormbalkon.de/',
    id: 410,
    imdb_id: 'tt0477877',
    original_language: 'de',
    original_title: 'Sommer vorm Balkon',
    overview:
      'When you read the title ‘Summer on the Balcony’ you probably think it will be a light Berlin summer comedy but it’s not. This film is an intimate study of two women friends who come to each other because of troubles with everyday life and with men and thus try to enjoy a life based on their ideas.',
    popularity: 4.116,
    poster_path: '/9zu21w5SwWDSHZI7P5fv8wJqUz5.jpg',
    production_companies: [
      {
        id: 96,
        logo_path: '/9ps82gVzUeNdkjmLzoGDQLiLDio.png',
        name: 'X Filme Creative Pool',
        origin_country: 'DE',
      },
      {
        id: 166,
        logo_path: null,
        name: 'Peter Rommel Productions',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'DE',
        name: 'Germany',
      },
    ],
    release_date: '2005-09-09',
    revenue: 0,
    runtime: 105,
    spoken_languages: [
      {
        english_name: 'German',
        iso_639_1: 'de',
        name: 'Deutsch',
      },
    ],
    status: 'Released',
    tagline: '',
    title: 'Summer in Berlin',
    video: false,
    vote_average: 6.681,
    vote_count: 36,
  },
  {
    adult: false,
    backdrop_path: '/7fEOKdQIfbkOxy0enLtpyPGUsTm.jpg',
    belongs_to_collection: null,
    budget: 8000000,
    genres: [
      {
        id: 18,
        name: 'Drama',
      },
      {
        id: 80,
        name: 'Crime',
      },
    ],
    homepage: '',
    id: 400,
    imdb_id: 'tt0114660',
    original_language: 'en',
    original_title: "Things to Do in Denver When You're Dead",
    overview:
      'Five different criminals face imminent death after botching a job quite badly.',
    popularity: 9.903,
    poster_path: '/oPp6Gbrasox66WyMvPS0k8OakQf.jpg',
    production_companies: [
      {
        id: 14,
        logo_path: '/m6AHu84oZQxvq7n1rsvMNJIAsMu.png',
        name: 'Miramax',
        origin_country: 'US',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1995-12-01',
    revenue: 529766,
    runtime: 116,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: 'Protect. Love. Honor. Avenge.',
    title: "Things to Do in Denver When You're Dead",
    video: false,
    vote_average: 6.523,
    vote_count: 305,
  },
  {
    adult: false,
    backdrop_path: '/3tWw50B1xXlCnJ9A7NX4nNzZF4j.jpg',
    belongs_to_collection: null,
    budget: 35000000,
    genres: [
      {
        id: 35,
        name: 'Comedy',
      },
      {
        id: 18,
        name: 'Drama',
      },
      {
        id: 10749,
        name: 'Romance',
      },
    ],
    homepage: 'http://www.devilwearspradamovie.com/',
    id: 350,
    imdb_id: 'tt0458352',
    original_language: 'en',
    original_title: 'The Devil Wears Prada',
    overview:
      "Andy moves to New York to work in the fashion industry. Her boss is extremely demanding, cruel and won't let her succeed if she doesn't fit into the high class elegant look of their magazine.",
    popularity: 94.046,
    poster_path: '/8912AsVuS7Sj915apArUFbv6F9L.jpg',
    production_companies: [
      {
        id: 444,
        logo_path: '/42UPdZl6B2cFXgNUASR8hSt9mpS.png',
        name: 'Dune Entertainment',
        origin_country: 'US',
      },
      {
        id: 445,
        logo_path: null,
        name: 'Major Studio Partners',
        origin_country: 'US',
      },
      {
        id: 682,
        logo_path: null,
        name: 'Peninsula Films',
        origin_country: '',
      },
      {
        id: 711,
        logo_path: '/tEiIH5QesdheJmDAqQwvtN60727.png',
        name: 'Fox 2000 Pictures',
        origin_country: 'US',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'FR',
        name: 'France',
      },
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '2006-06-29',
    revenue: 326551094,
    runtime: 109,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
      {
        english_name: 'French',
        iso_639_1: 'fr',
        name: 'Français',
      },
    ],
    status: 'Released',
    tagline:
      "Meet Andy Sachs. A million girls would kill to have her job. She's not one of them.",
    title: 'The Devil Wears Prada',
    video: false,
    vote_average: 7.381,
    vote_count: 10335,
  },
  {
    adult: false,
    backdrop_path: '/bHePzkyRcMhnab2qZbhj1bCElnf.jpg',
    belongs_to_collection: null,
    budget: 6000000,
    genres: [
      {
        id: 35,
        name: 'Comedy',
      },
      {
        id: 18,
        name: 'Drama',
      },
      {
        id: 14,
        name: 'Fantasy',
      },
    ],
    homepage: 'http://www.lasciencedesreves-lefilm.com/accueil.htm',
    id: 300,
    imdb_id: 'tt0354899',
    original_language: 'fr',
    original_title: 'La Science des rêves',
    overview:
      'A man entranced by his dreams and imagination is lovestruck with a French woman and feels he can show her his world.',
    popularity: 11.495,
    poster_path: '/1qCq228LsNtUseCnNE7Naw6NBUz.jpg',
    production_companies: [
      {
        id: 9,
        logo_path: '/nda3dTUYdDrJ6rZqBpYvY865aDv.png',
        name: 'Gaumont',
        origin_country: 'FR',
      },
      {
        id: 104,
        logo_path: '/9aotxauvc9685tq9pTcRJszuT06.png',
        name: 'Canal+',
        origin_country: 'FR',
      },
      {
        id: 591,
        logo_path: '/q5I5RDwMEiqoNmfaJgd2LraEOJY.png',
        name: 'France 3 Cinéma',
        origin_country: 'FR',
      },
      {
        id: 6586,
        logo_path: null,
        name: 'TPS Star',
        origin_country: 'FR',
      },
      {
        id: 11911,
        logo_path: null,
        name: 'Partizan Films',
        origin_country: '',
      },
      {
        id: 11912,
        logo_path: null,
        name: 'Mikado Film',
        origin_country: 'IT',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'FR',
        name: 'France',
      },
      {
        iso_3166_1: 'IT',
        name: 'Italy',
      },
    ],
    release_date: '2006-02-11',
    revenue: 9524340,
    runtime: 105,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
      {
        english_name: 'French',
        iso_639_1: 'fr',
        name: 'Français',
      },
      {
        english_name: 'Spanish',
        iso_639_1: 'es',
        name: 'Español',
      },
    ],
    status: 'Released',
    tagline: 'Close your eyes. Open your heart.',
    title: 'The Science of Sleep',
    video: false,
    vote_average: 7.051,
    vote_count: 623,
  },
  {
    adult: false,
    backdrop_path: '/yujmMuRgqlT50sE8y9iuxFIK5hs.jpg',
    belongs_to_collection: null,
    budget: 2500000,
    genres: [
      {
        id: 35,
        name: 'Comedy',
      },
      {
        id: 18,
        name: 'Drama',
      },
      {
        id: 10749,
        name: 'Romance',
      },
    ],
    homepage: 'http://www.foxsearchlight.com/gardenstate/',
    id: 401,
    imdb_id: 'tt0333766',
    original_language: 'en',
    original_title: 'Garden State',
    overview:
      'Andrew returns to his hometown for the funeral of his mother, a journey that reconnects him with past friends. The trip coincides with his decision to stop taking his powerful antidepressants. A chance meeting with Sam - a girl also suffering from various maladies - opens up the possibility of rekindling emotional attachments, confronting his psychologist father, and perhaps beginning a new life.',
    popularity: 12.299,
    poster_path: '/h3iqYiGS6F3y7GxaS4AT8nFxZ2i.jpg',
    production_companies: [
      {
        id: 14,
        logo_path: '/m6AHu84oZQxvq7n1rsvMNJIAsMu.png',
        name: 'Miramax',
        origin_country: 'US',
      },
      {
        id: 43,
        logo_path: '/4RgIPr55kBakgupWkzdDxqXJEqr.png',
        name: 'Fox Searchlight Pictures',
        origin_country: 'US',
      },
      {
        id: 215,
        logo_path: '/tQyeqkCj24krhY2W8qeAztcOS37.png',
        name: 'Double Feature Films',
        origin_country: 'US',
      },
      {
        id: 216,
        logo_path: null,
        name: 'Jersey Films',
        origin_country: 'US',
      },
      {
        id: 11728,
        logo_path: null,
        name: 'Camelot Pictures',
        origin_country: '',
      },
      {
        id: 11729,
        logo_path: null,
        name: "Large's Ark Productions",
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '2004-07-28',
    revenue: 26781723,
    runtime: 102,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: '',
    title: 'Garden State',
    video: false,
    vote_average: 7.098,
    vote_count: 1538,
  },
  {
    adult: false,
    backdrop_path: '/5Pl47mB0Jnrg4oHoO0sVdJ6WMRL.jpg',
    belongs_to_collection: null,
    budget: 0,
    genres: [
      {
        id: 18,
        name: 'Drama',
      },
    ],
    homepage: '',
    id: 405,
    imdb_id: 'tt0047528',
    original_language: 'it',
    original_title: 'La strada',
    overview:
      "When Gelsomina, a naïve young woman, is purchased from her impoverished mother by brutish circus strongman Zampanò to be his wife and partner, she loyally endures her husband's coldness and abuse as they travel the Italian countryside performing together. Soon Zampanò must deal with his jealousy and conflicted feelings about Gelsomina when she finds a kindred spirit in Il Matto, the carefree circus fool, and contemplates leaving Zampanò.",
    popularity: 12.252,
    poster_path: '/cDWISzYLg7NTyfXHoPLm7aNX2Wa.jpg',
    production_companies: [
      {
        id: 217,
        logo_path: null,
        name: 'Ponti-De Laurentiis Cinematografica',
        origin_country: 'IT',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'IT',
        name: 'Italy',
      },
    ],
    release_date: '1954-09-23',
    revenue: 0,
    runtime: 115,
    spoken_languages: [
      {
        english_name: 'Italian',
        iso_639_1: 'it',
        name: 'Italiano',
      },
    ],
    status: 'Released',
    tagline: 'Filmed in Italy - where it happened!',
    title: 'La Strada',
    video: false,
    vote_average: 7.969,
    vote_count: 843,
  },
  {
    adult: false,
    backdrop_path: '/v7baGyne7CsLxnM2maMwIxKZdVF.jpg',
    belongs_to_collection: null,
    budget: 20000000,
    genres: [
      {
        id: 80,
        name: 'Crime',
      },
      {
        id: 18,
        name: 'Drama',
      },
    ],
    homepage: '',
    id: 505,
    imdb_id: 'tt0097626',
    original_language: 'en',
    original_title: 'Johnny Handsome',
    overview:
      'A career criminal who has been deformed since birth is given a new face by a kindly doctor and paroled from prison. It appears that he has gone straight, but he is really planning his revenge on the man who killed his mentor and sent him to prison.',
    popularity: 12.131,
    poster_path: '/hdEIkpL17rvfZH0l34FJ8H9LAa.jpg',
    production_companies: [
      {
        id: 275,
        logo_path: '/2MxNWlN5b3UXt1OfmznsWEQzFwq.png',
        name: 'Carolco Pictures',
        origin_country: 'US',
      },
      {
        id: 276,
        logo_path: null,
        name: 'Guber/Peters Company',
        origin_country: '',
      },
      {
        id: 277,
        logo_path: null,
        name: 'Roven Productions',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1989-09-12',
    revenue: 7237794,
    runtime: 94,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline:
      "They changed his looks, his life and his future... but they couldn't change his past .",
    title: 'Johnny Handsome',
    video: false,
    vote_average: 6.275,
    vote_count: 207,
  },
  {
    adult: false,
    backdrop_path: '/qUq3QTr2KLvGIcN0GaaaYx9bbyH.jpg',
    belongs_to_collection: null,
    budget: 3000000,
    genres: [
      {
        id: 18,
        name: 'Drama',
      },
    ],
    homepage: '',
    id: 510,
    imdb_id: 'tt0073486',
    original_language: 'en',
    original_title: "One Flew Over the Cuckoo's Nest",
    overview:
      'A petty criminal fakes insanity to serve his sentence in a mental ward rather than prison. He soon finds himself as a leader to the other patients—and an enemy to the cruel, domineering nurse who runs the ward.',
    popularity: 29.985,
    poster_path: '/3jcbDmRFiQ83drXNOvRDeKHxS0C.jpg',
    production_companies: [
      {
        id: 286,
        logo_path: null,
        name: 'Fantasy Films',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'US',
        name: 'United States of America',
      },
    ],
    release_date: '1975-11-19',
    revenue: 108981275,
    runtime: 133,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: "If he's crazy, what does that make you?",
    title: "One Flew Over the Cuckoo's Nest",
    video: false,
    vote_average: 8.429,
    vote_count: 8926,
  },
  {
    adult: false,
    backdrop_path: '/xQa198uEb8DLwQntDwO9jlilXcC.jpg',
    belongs_to_collection: null,
    budget: 0,
    genres: [
      {
        id: 18,
        name: 'Drama',
      },
    ],
    homepage: '',
    id: 511,
    imdb_id: 'tt0072446',
    original_language: 'pl',
    original_title: 'Ziemia obiecana',
    overview:
      'The Polish film based on the book of the same name by Wladyslaw Reymont. Taking place in the nineteenth century town of Łódź, Poland, three friends want to make a lot of money by building and investing in a textile factory. An exceptional portrait of rapid industrial expansion shown through the eyes of one Polish town.',
    popularity: 4.732,
    poster_path: '/pjk8K5MpQJX0XczTC2KOVWNj0lC.jpg',
    production_companies: [
      {
        id: 52,
        logo_path: null,
        name: 'Film Polski Film Agency',
        origin_country: '',
      },
      {
        id: 6804,
        logo_path: null,
        name: 'Zespól Filmowy "X"',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'PL',
        name: 'Poland',
      },
    ],
    release_date: '1975-02-21',
    revenue: 0,
    runtime: 170,
    spoken_languages: [
      {
        english_name: 'German',
        iso_639_1: 'de',
        name: 'Deutsch',
      },
      {
        english_name: 'Russian',
        iso_639_1: 'ru',
        name: 'Pусский',
      },
      {
        english_name: 'Yiddish',
        iso_639_1: 'yi',
        name: '',
      },
      {
        english_name: 'Polish',
        iso_639_1: 'pl',
        name: 'Polski',
      },
    ],
    status: 'Released',
    tagline: '',
    title: 'The Promised Land',
    video: false,
    vote_average: 7.0,
    vote_count: 50,
  },
  {
    adult: false,
    backdrop_path: '/8qPG3AjLtletf1K4g8iGhKwHQSc.jpg',
    belongs_to_collection: null,
    budget: 4000000,
    genres: [
      {
        id: 35,
        name: 'Comedy',
      },
      {
        id: 9648,
        name: 'Mystery',
      },
    ],
    homepage: 'http://www.scoopmovie.net/',
    id: 512,
    imdb_id: 'tt0457513',
    original_language: 'en',
    original_title: 'Scoop',
    overview:
      'An American journalism student in London scoops a big story, and begins an affair with an aristocrat as the incident unfurls.',
    popularity: 12.377,
    poster_path: '/aHvZYoQNRTMrfs46pj64b9GrbaK.jpg',
    production_companies: [
      {
        id: 288,
        logo_path: '/wdmwQuV4R1MIr8A78izZkC184uC.png',
        name: 'BBC Films',
        origin_country: 'GB',
      },
      {
        id: 290,
        logo_path: '/Q8mw2AOQQc8Qg0uNwLWq86DVZv.png',
        name: 'Ingenious Media',
        origin_country: 'GB',
      },
      {
        id: 291,
        logo_path: null,
        name: 'Perdido Prod.',
        origin_country: '',
      },
      {
        id: 7316,
        logo_path: null,
        name: 'Phoenix Wiley',
        origin_country: '',
      },
      {
        id: 136057,
        logo_path: null,
        name: 'Jelly Roll Production',
        origin_country: '',
      },
    ],
    production_countries: [
      {
        iso_3166_1: 'GB',
        name: 'United Kingdom',
      },
    ],
    release_date: '2006-07-27',
    revenue: 31584901,
    runtime: 96,
    spoken_languages: [
      {
        english_name: 'English',
        iso_639_1: 'en',
        name: 'English',
      },
    ],
    status: 'Released',
    tagline: 'The perfect man. The perfect story. The perfect murder.',
    title: 'Scoop',
    video: false,
    vote_average: 6.589,
    vote_count: 1405,
  },
];
