import { FetchMovie } from './js/fetch';
import { fechMuviQueri } from './js/fetch';
import { renderCards } from './js/render-cards';
// import { API_KEY, URL } from './js/fetch';
import './js/open-modal';
import './js/moviesByRating';
import './js/moviesBySubmit';
import './js/adding-watched-movies';
import './js/loader';
import './js/button-back';
