import './js/modal-footer';
import './js/add-to-watched';
import './js/add-to-queue';
import './js/loader';
import './js/empty-page';
// import './js/firebaseUI';
import './js/on-myLibrary-click';
import './js/modernizr-custom';
import './js/modal-footer';
import './js/open-modal-gallery';
import './js/switch-theme-library';
